description = "Default permissions for the win-screen plugin."
permissions = [
  "allow-capture-fullscreen",
  "allow-capture-region",
  "allow-capture-monitor",
  "allow-capture-window",
  "allow-list-monitors",
  "allow-list-windows",
  "allow-capture-fullscreen-to-pin",
  "allow-capture-region-to-pin",
  "allow-capture-monitor-to-pin",
  "allow-capture-window-to-pin",
  "allow-interactive-capture-to-pin",
  "allow-start-interactive-capture",
  "allow-select-interactive-capture",
  "allow-pin-image",
  "allow-pin-from-clipboard",
  "allow-list-pins",
  "allow-copy-pin",
  "allow-save-pin",
  "allow-set-pin-opacity",
  "allow-close-pin",
  "allow-start-recording",
  "allow-stop-recording",
]
