[package]
name = "win-screen-tauri"
version = "0.1.0"
description = "Tauri plugin wrapper for win-screen-core."
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
image.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri.workspace = true
win-screen-core = { path = "../win-screen-core" }
